[project]
name = "friday"
version = "0.1.0"
description = "AI assistant for the Freya ecosystem"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.4.5",
    "ruff>=0.8.5",
    "websocket-client>=1.8.0",
]
